# Generated by Django 4.1 on 2023-04-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='item',
            name='bodyType',
            field=models.CharField(default='new', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(default='new', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(default='new', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='distance',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='modal',
            field=models.CharField(default='new', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='paymentoption',
            field=models.CharField(default='new', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.CharField(default='new', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='transmissionType',
            field=models.CharField(default='new', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='year',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(default='new', max_length=255),
        ),
    ]
