# Generated by Django 4.1 on 2023-04-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_item_distance_alter_item_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='distance',
        ),
    ]
