# Generated by Django 4.1 on 2023-04-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_remove_item_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='distance',
            field=models.IntegerField(default=1),
        ),
    ]
