# Generated by Django 4.1 on 2023-04-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_item_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='distance',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
