# Generated by Django 4.1 on 2023-04-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_alter_item_bodytype_alter_item_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
