# Generated by Django 4.1 on 2023-05-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_item_created_item_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='installment',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='maxdistance',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='mindistance',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
